pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: docker login "$(ACR_REGISTRY)" -u "$(ACR_USER)" -p "$(ACR_PASSWORD)"
  displayName: Docker Login
- script: docker build . -t "$(DOCKER_IMAGE_NAME)"
  displayName: Docker Build
- script: docker run --rm -i "$(DOCKER_IMAGE_NAME)" /bin/bash -c "black . --check --exclude .env" 
  displayName: Lint with Black
- script: docker run --rm "$(DOCKER_IMAGE_NAME)" 
  displayName: Test with pytest
- script: docker push "$(DOCKER_IMAGE_NAME)"
  displayName: Publish Docker Image